version: '3.9'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: yourStrong(!)Password
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - dbdata:/var/opt/mssql/data
volumes:
  dbdata: